# Generated by Django 6.0.5 on 2026-09-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='conversation_id',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='chat.conversation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
