# Generated by Django 6.0.5 on 2026-09-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('media_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
